export const GAMES = [
  {
    slug: "thread-the-needle",
    title: "Thread the Needle",
    tag: "precision",
    blurb: "Guide a physics-string through a tiny needle eye. It flicks. Your hand shakes.",
    emoji: "🪡",
    ready: true,
  },
  {
    slug: "math-duel",
    title: "Math Duel",
    tag: "race",
    blurb: "Race a human-like opponent through 10 mental-math problems. First to ten wins.",
    emoji: "⚔️",
    ready: true,
  },
  {
    slug: "perfect-circle",
    title: "Perfect Shape",
    tag: "drawing",
    blurb: "Draw a circle, square, or rectangle in one stroke. Scored on how close to perfect.",
    emoji: "⭕",
    ready: true,
  },
  {
    slug: "reaction-time",
    title: "Reaction Time",
    tag: "reflex",
    blurb: "Wait for green. Click as fast as you can. Best of 5 average.",
    emoji: "⚡",
    ready: true,
  },
  {
    slug: "water-drop",
    title: "Water Drop",
    tag: "physics",
    blurb: "Fill the glass. Don't overflow. Play solo or with up to 4 bot rivals.",
    emoji: "💧",
    ready: true,
  },
  {
    slug: "stop-the-bar",
    title: "Stop the Bar",
    tag: "timing",
    blurb: "Tap when the sliding bar hits the green zone. Every level, the zone shrinks.",
    emoji: "🎯",
    ready: false,
  },
  {
    slug: "aim-trainer",
    title: "Aim Trainer",
    tag: "skill",
    blurb: "Pop 30 targets as fast as you can. Accuracy matters.",
    emoji: "🕹️",
    ready: false,
  },
  {
    slug: "higher-lower",
    title: "Higher or Lower",
    tag: "trivia",
    blurb: "Is X bigger than Y? Populations, salaries, view counts — keep the streak alive.",
    emoji: "📈",
    ready: false,
  },
  {
    slug: "cursor-maze",
    title: "Cursor Maze",
    tag: "precision",
    blurb: "Navigate the mouse from start to end without touching a wall.",
    emoji: "🧭",
    ready: false,
  },
  {
    slug: "wire-loop",
    title: "Wire Loop",
    tag: "precision",
    blurb: "Trace the wire without touching it. Steady hand only.",
    emoji: "🔌",
    ready: false,
  },
  {
    slug: "fruit-merge",
    title: "Fruit Merge",
    tag: "physics",
    blurb: "Drop and merge fruit. Same fruit combines. Don't spill over the top.",
    emoji: "🍉",
    ready: false,
  },
  {
    slug: "guess-the-year",
    title: "Guess the Year",
    tag: "trivia",
    blurb: "See a photo, guess the year. Closer = more points.",
    emoji: "📅",
    ready: false,
  },
  {
    slug: "password-game",
    title: "Password Game",
    tag: "puzzle",
    blurb: "Increasingly absurd rules for one password.",
    emoji: "🔐",
    ready: false,
  },
];
