export const GAMES = [
  {
    slug: "thread-the-needle",
    title: "Thread the Needle",
    tag: "precision",
    blurb: "Guide a physics-string through a tiny needle eye. It flicks. Your hand shakes.",
    emoji: "🪡",
    ready: true,
  },
  {
    slug: "math-duel",
    title: "Math Duel",
    tag: "race",
    blurb: "Race a human-like opponent through 10 mental-math problems. First to ten wins.",
    emoji: "⚔️",
    ready: true,
  },
  {
    slug: "perfect-circle",
    title: "Perfect Shape",
    tag: "drawing",
    blurb: "Draw a circle, square, or rectangle in one stroke. Scored on how close to perfect.",
    emoji: "⭕",
    ready: true,
  },
  {
    slug: "reaction-time",
    title: "Reaction Time",
    tag: "reflex",
    blurb: "Wait for green. Click as fast as you can. Best of 5 average.",
    emoji: "⚡",
    ready: true,
  },
  {
    slug: "water-drop",
    title: "Water Drop",
    tag: "physics",
    blurb: "Fill the glass. Don't overflow. Play solo or with up to 4 bot rivals.",
    emoji: "💧",
    ready: true,
  },
  {
    slug: "rps-duel",
    title: "RPS Duel",
    tag: "race",
    blurb: "Rock, paper, scissors. Best of 5. Bot or friend.",
    emoji: "✊",
    ready: true,
  },
  {
    slug: "draw-guess",
    title: "Draw & Guess",
    tag: "race",
    blurb: "One player draws, others race to guess. 2–4 players. Skribbl in your pocket.",
    emoji: "🎨",
    ready: true,
  },
  {
    slug: "trivia-rumble",
    title: "Trivia Rumble",
    tag: "race",
    blurb: "2–4 player trivia race. Fastest correct answer wins the round. First to the finish takes the match.",
    emoji: "🧠",
    ready: true,
  },
  {
    slug: "odd-one-out",
    title: "Odd One Out",
    tag: "trivia",
    blurb: "Grid of dots. One is different. First to spot it wins the round. Colors get closer each round.",
    emoji: "👁️",
    ready: true,
  },
  {
    slug: "chess",
    title: "Chess",
    tag: "race",
    blurb: "Play chess vs a bot or a friend. Free forever. Stockfish analysis coming next.",
    emoji: "♞",
    ready: true,
  },
  {
    slug: "stop-the-bar",
    title: "Stop the Bar",
    tag: "timing",
    blurb: "Tap when the sliding bar hits the green zone. Every level, the zone shrinks.",
    emoji: "🎯",
    ready: false,
  },
  {
    slug: "aim-trainer",
    title: "Aim Trainer",
    tag: "skill",
    blurb: "Pop 30 targets as fast as you can. Miss = penalty. Aimlab in your browser.",
    emoji: "🎯",
    ready: true,
  },
  {
    slug: "higher-lower",
    title: "Higher or Lower",
    tag: "trivia",
    blurb: "Which term gets more Google searches? Keep the streak alive.",
    emoji: "📈",
    ready: true,
  },
  {
    slug: "password-game",
    title: "Password Game",
    tag: "puzzle",
    blurb: "Increasingly absurd rules for one password. Can you satisfy them all?",
    emoji: "🔐",
    ready: true,
  },
  {
    slug: "emojile",
    title: "Emojile",
    tag: "trivia",
    blurb: "A phrase in emoji. You have 5 guesses. New puzzle every day.",
    emoji: "🧩",
    ready: true,
  },
  {
    slug: "cursor-maze",
    title: "Cursor Maze",
    tag: "precision",
    blurb: "Navigate the mouse from start to end without touching a wall.",
    emoji: "🧭",
    ready: false,
  },
  {
    slug: "wire-loop",
    title: "Wire Loop",
    tag: "precision",
    blurb: "Trace the wire without touching it. Steady hand only.",
    emoji: "🔌",
    ready: false,
  },
  {
    slug: "fruit-merge",
    title: "Fruit Merge",
    tag: "physics",
    blurb: "Drop and merge fruit. Same fruit combines. Don't overflow the box.",
    emoji: "🍉",
    ready: true,
  },
  {
    slug: "guess-the-year",
    title: "Guess the Year",
    tag: "trivia",
    blurb: "See a photo, guess the year. Closer = more points.",
    emoji: "📅",
    ready: false,
  },
];
