// Approximate global monthly Google search volumes (in thousands).
// These are ROUGH approximations — the game just needs relative ordering to feel right.
export const GOOGLE_SEARCHES = [
  { term: "youtube",         volume: 1200000 },
  { term: "facebook",        volume: 950000 },
  { term: "google",          volume: 700000 },
  { term: "gmail",           volume: 380000 },
  { term: "amazon",          volume: 320000 },
  { term: "weather",         volume: 280000 },
  { term: "translate",       volume: 210000 },
  { term: "chatgpt",         volume: 260000 },
  { term: "netflix",         volume: 210000 },
  { term: "wordle",          volume: 45000 },
  { term: "tiktok",          volume: 180000 },
  { term: "instagram",       volume: 240000 },
  { term: "whatsapp",        volume: 190000 },
  { term: "twitter",         volume: 90000 },
  { term: "reddit",          volume: 70000 },
  { term: "linkedin",        volume: 80000 },
  { term: "pornhub",         volume: 165000 },
  { term: "spotify",         volume: 65000 },
  { term: "twitch",          volume: 55000 },
  { term: "discord",         volume: 45000 },
  { term: "wikipedia",       volume: 60000 },
  { term: "ebay",            volume: 55000 },
  { term: "roblox",          volume: 50000 },
  { term: "minecraft",       volume: 30000 },
  { term: "fortnite",        volume: 12000 },
  { term: "bitcoin",         volume: 10000 },
  { term: "iphone",          volume: 8500 },
  { term: "samsung",         volume: 6800 },
  { term: "tesla",           volume: 6000 },
  { term: "apple",           volume: 5500 },
  { term: "elon musk",       volume: 3400 },
  { term: "cristiano ronaldo", volume: 5500 },
  { term: "messi",           volume: 2800 },
  { term: "taylor swift",    volume: 3600 },
  { term: "kim kardashian",  volume: 1900 },
  { term: "donald trump",    volume: 3300 },
  { term: "joe biden",       volume: 1800 },
  { term: "recipes",         volume: 3800 },
  { term: "pizza",           volume: 2600 },
  { term: "cats",            volume: 1500 },
  { term: "dogs",            volume: 1300 },
  { term: "memes",           volume: 1100 },
  { term: "porn",            volume: 90000 },
  { term: "sex",             volume: 45000 },
  { term: "corona virus",    volume: 900 },
  { term: "world cup",       volume: 2400 },
  { term: "olympics",        volume: 700 },
  { term: "nba",             volume: 1600 },
  { term: "premier league",  volume: 900 },
  { term: "cricket",         volume: 3200 },
  { term: "football",        volume: 1800 },
  { term: "javascript",      volume: 900 },
  { term: "python",          volume: 1400 },
  { term: "react",           volume: 350 },
  { term: "nodejs",          volume: 90 },
  { term: "html",            volume: 780 },
  { term: "css",             volume: 650 },
  { term: "google maps",     volume: 68000 },
  { term: "youtube to mp3",  volume: 22000 },
  { term: "flights",         volume: 5500 },
  { term: "hotels",          volume: 3800 },
  { term: "starbucks",       volume: 4200 },
  { term: "mcdonalds",       volume: 5400 },
  { term: "walmart",         volume: 44000 },
  { term: "target",          volume: 12000 },
  { term: "ikea",            volume: 6600 },
  { term: "zara",            volume: 3200 },
  { term: "adidas",          volume: 3800 },
  { term: "nike",            volume: 6100 },
  { term: "gucci",           volume: 1700 },
  { term: "rolex",           volume: 1500 },
  { term: "how to tie a tie", volume: 220 },
  { term: "how to kiss",     volume: 40 },
  { term: "how to lose weight", volume: 480 },
];
