// General-knowledge trivia bank. Each question: { q, options: [4 strings], correct: index 0-3 }
export const QUESTIONS = [
  { q: "which planet is known as the red planet?", options: ["venus","mars","jupiter","mercury"], correct: 1 },
  { q: "what is the capital of australia?", options: ["sydney","melbourne","canberra","perth"], correct: 2 },
  { q: "who painted the mona lisa?", options: ["van gogh","picasso","da vinci","monet"], correct: 2 },
  { q: "how many strings does a standard guitar have?", options: ["4","5","6","7"], correct: 2 },
  { q: "what is the largest ocean on earth?", options: ["atlantic","indian","arctic","pacific"], correct: 3 },
  { q: "in which year did world war ii end?", options: ["1943","1945","1947","1950"], correct: 1 },
  { q: "what is the chemical symbol for gold?", options: ["go","gd","au","ag"], correct: 2 },
  { q: "which is the smallest prime number?", options: ["0","1","2","3"], correct: 2 },
  { q: "the great wall of china is in which country?", options: ["japan","china","korea","mongolia"], correct: 1 },
  { q: "what animal is the fastest on land?", options: ["lion","cheetah","horse","gazelle"], correct: 1 },
  { q: "how many continents are there?", options: ["5","6","7","8"], correct: 2 },
  { q: "who wrote romeo and juliet?", options: ["shakespeare","dickens","austen","milton"], correct: 0 },
  { q: "what does 'www' stand for?", options: ["world wide web","world wired web","wide web world","world web wide"], correct: 0 },
  { q: "which vitamin does the sun help produce?", options: ["a","b","c","d"], correct: 3 },
  { q: "what is the tallest mountain in the world?", options: ["k2","kilimanjaro","everest","denali"], correct: 2 },
  { q: "the mariana trench is in which ocean?", options: ["atlantic","indian","pacific","arctic"], correct: 2 },
  { q: "which language has the most native speakers?", options: ["english","spanish","mandarin","hindi"], correct: 2 },
  { q: "who invented the light bulb?", options: ["edison","tesla","bell","newton"], correct: 0 },
  { q: "what is the smallest country in the world?", options: ["monaco","vatican city","san marino","liechtenstein"], correct: 1 },
  { q: "how many bones are in the adult human body?", options: ["186","206","226","246"], correct: 1 },
  { q: "what is the currency of japan?", options: ["yuan","won","yen","ringgit"], correct: 2 },
  { q: "which planet has the most moons?", options: ["jupiter","saturn","uranus","neptune"], correct: 1 },
  { q: "which country invented pizza?", options: ["italy","france","greece","turkey"], correct: 0 },
  { q: "how many colors are in a rainbow?", options: ["5","6","7","8"], correct: 2 },
  { q: "what is the largest desert in the world?", options: ["sahara","gobi","antarctica","kalahari"], correct: 2 },
  { q: "who was the first person to walk on the moon?", options: ["buzz aldrin","yuri gagarin","neil armstrong","john glenn"], correct: 2 },
  { q: "which programming language is named after a snake?", options: ["ruby","python","java","cobra"], correct: 1 },
  { q: "the eiffel tower is in which city?", options: ["london","rome","paris","berlin"], correct: 2 },
  { q: "which sport uses a shuttlecock?", options: ["tennis","badminton","squash","cricket"], correct: 1 },
  { q: "what is the square root of 144?", options: ["10","11","12","13"], correct: 2 },
  { q: "which gas do plants primarily absorb?", options: ["oxygen","nitrogen","carbon dioxide","hydrogen"], correct: 2 },
  { q: "the taj mahal is in which country?", options: ["india","pakistan","iran","turkey"], correct: 0 },
  { q: "who is the greek god of the sea?", options: ["zeus","hades","poseidon","apollo"], correct: 2 },
  { q: "which country gifted the statue of liberty to the usa?", options: ["england","france","spain","italy"], correct: 1 },
  { q: "how many players are on a soccer team on the field?", options: ["9","10","11","12"], correct: 2 },
  { q: "what is the hardest natural substance on earth?", options: ["gold","iron","diamond","platinum"], correct: 2 },
  { q: "which sea creature has three hearts?", options: ["octopus","whale","dolphin","shark"], correct: 0 },
  { q: "how many minutes are in a full day?", options: ["1200","1440","1560","1680"], correct: 1 },
  { q: "which country has the largest population?", options: ["china","india","usa","indonesia"], correct: 1 },
  { q: "what is the boiling point of water in celsius?", options: ["90","95","100","110"], correct: 2 },
  { q: "which famous ship sank in 1912?", options: ["lusitania","titanic","britannic","olympic"], correct: 1 },
  { q: "what is the name of our galaxy?", options: ["andromeda","milky way","triangulum","orion"], correct: 1 },
  { q: "which instrument has 88 keys?", options: ["organ","piano","harpsichord","xylophone"], correct: 1 },
  { q: "what is the largest mammal?", options: ["elephant","blue whale","giraffe","polar bear"], correct: 1 },
  { q: "which planet is closest to the sun?", options: ["venus","earth","mercury","mars"], correct: 2 },
  { q: "what element does 'o' represent on the periodic table?", options: ["gold","osmium","oxygen","oganesson"], correct: 2 },
  { q: "how many players in a basketball team on court?", options: ["4","5","6","7"], correct: 1 },
  { q: "what year did the berlin wall fall?", options: ["1987","1989","1991","1993"], correct: 1 },
  { q: "which country produces the most coffee?", options: ["colombia","vietnam","brazil","ethiopia"], correct: 2 },
  { q: "the amazon rainforest is mostly in which country?", options: ["peru","brazil","colombia","venezuela"], correct: 1 },
];
